### ISSUE TITLE
io.getunleash.UnleashException: Could not fetch toggles 

### ISSUE THREAD

**Issue by idomiralin** [Unleash/unleash-client-java#144]
Not able to fetch toggles from gitlab because of this error:

sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

With Node client it is possible to fetch the toggles, because of this option:

httpOptions: {
    rejectUnauthorized: false
  },

How can we set strict ssl false or rejectUnauthorized false also in the java client so that we don't receive an PKIX certification exception? Is there any equivalent in Java?

Could you please help?

I tried also this tutorial to fetch the toggles

https://thepracticaldeveloper.com/practical-guide-feature-toggles-spring-boot/

**Comment by checketts** [comment]
What JVM are you using? Is the root cause that the KVM is so old it doesn't have current cert chains?

**Comment by idomiralin** [comment]
I am using java 8. I am trying this in corporate. But isn't there something like rejectUnauthorized also for the java client as it is in the node client?

**Comment by checketts** [comment]
I don't see a way in the current code that allows disabling SSL.  You should be able to update your Java 8 to a later update that has the current certs. 

It appears that you when you create the `DefaultUnleash` you can pass in a `FeatureToggleRepository` and in the repository pass in your own `HttpToggleFetcher`, since the `ToggleFetcher` is an interface, you could create your own that ignores the cert issue.

Updating your Java 8 might be simpler. ;)

**Comment by supriya-tw** [comment]
@idomiralin Were you able to find any solution? I am running into similar issue. I get exception -_sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target_ while following step - https://docs.getunleash.io/sdks/java_sdk#step-2-create-a-new-unleash-instance


I believe I do not need client secret as I am leveraging gitlab hosted unleash feature flags.

Any insights would be helpful.
