### ISSUE TITLE
Filter for tags

### ISSUE THREAD

**Issue by AldinDuraki** [Unleash/unleash-client-java#235]
### Describe the feature request

As discussed in [Slack](https://unleash-community.slack.com/archives/C03GZBSJV9A/p1702489252781259) i would love to see the possibility to get all feature toggles with a specific Tag. There are a few use cases where this would come in handy.

The functionality is already there `/api/client/features?tag=simple:mytag` but got removed from the sdk. Please readd this.

**Comment by sighphyre** [comment]
Hey @AldinDuraki, thanks for opening an issue. If I recall correctly, we removed this because it wasn't getting used much and was contributing to maintenance overhead. If you have a pro or enterprise, you should be able to do this with token filtering.

A single request probably isn't enough for us to bring this back but we've happy to leave the issue open and move on it if it gets enough interest!
