### ISSUE TITLE
Allow lazy-evaluated context properties

### ISSUE THREAD

**Issue by derari** [Unleash/unleash-client-java#252]
### Describe the feature request

In addition to providing context properties by value, I want to provide a supplier that only gets evaluated when it the property value actually needed (i.e., when the checked featured has a rollout strategy that needs this value to evalute the status).

### Background

I have a number of context properties that are not super expensive to compute each on their own, but they add up all together.
However, most of the time only one of those properties is actually needed, if any.

To avoid unnecessary workload, I would like to tell Unleash to only evalute such properties if necessary.

### Solution suggestions

UnleashContext gets a `Map<String, Supplier<String>> lazyProperties` and `properties.get` is accordingly replaced with `properties.computeIfAbsent`

**Comment by gastonfournier** [comment]
Hi @derari, this is an interesting suggestion and we have a similar one for edge: https://github.com/Unleash/unleash-edge/issues/493. 

In the java client sdk, you should be able to use [UnleashContextProvider](https://github.com/Unleash/unleash-client-java?tab=readme-ov-file#2-via-an-unleashcontextprovider) for fetching external data. It's a bit of an overkill if you just want to do this for a few properties of the context, but let me know if this would solve your need because we'd like to take our time to think how to solve this in a way that works for all our SDKs.

**Comment by derari** [comment]
If I understand you correctly, the context provider is only called when the toggle actually depends on a context property, and will not be called if the feature is enabled or disabled for everyone. This does improve the situation a bit, but it does not help when I have many properties of which only one is needed.

**Comment by gastonfournier** [comment]
> If I understand you correctly, the context provider is only called when the toggle actually depends on a context property, and will not be called if the feature is enabled or disabled for everyone

I'm not sure we have the same understanding, let me try to explain how I see it:
Context provider is needed before the flag evaluation, it provides the context that the flag needs to check whether it's enabled or not. It's true, that you may have to provide all the context even when only 1 property is fetched asynchronously, but it's trade off. 

Maybe it's better if we can work/talk on a small snippet of code.

**Comment by gastonfournier** [comment]
Here's a test https://github.com/Unleash/unleash-client-java/pull/253/files

It shows:
1. A constraint on a flag that is only enabled when the version is greater than `1.2.2`
2. The version is fetched asynchronously and added to the context, while other properties such as the user id are already provided

**Comment by derari** [comment]
> It's true, that you may have to provide all the context even when only 1 property is fetched asynchronously, but it's trade off.

Understood. What I am looking for would be something like this

```java
        ...
        when(contextProvider.getContext())
            .thenAnswer((Answer<UnleashContext>) invocationOnMock ->
                UnleashContext.builder()
                    .userId("123")
                    .addProperty("version", () -> versionFetcher.getVersion())
                    .addProperty("productCode", () -> productFetcher.getProductCode())
                    .build()
            );

        verify(versionFetcher, times(0)).getVersion();
        assertThat(sut.isEnabled(toggleName)).isTrue();
        verify(versionFetcher, times(1)).getVersion();
        verify(productFetcher, times(0)).getProductCode(); // never called because it is not used by the activation strategy
    }
```

**Comment by gastonfournier** [comment]
Hi @derari it's an interesting case. I think we always considered that the context you send to the feature is the context the feature needs, but because in your code you know nothing about the activation strategy you can't predict which properties would be needed, so delaying that can save some time.

We'll have to think about it with the team, cause that would change how activation strategies work which would have an impact in all our SDKs. From the top of my head, this is not something we'll be implementing soon, but I'll have to talk to the team.

**Comment by FredrikOseberg** [comment]
> Hi [@derari](https://github.com/derari) it's an interesting case. I think we always considered that the context you send to the feature is the context the feature needs, but because in your code you know nothing about the activation strategy you can't predict which properties would be needed, so delaying that can save some time.
> 
> We'll have to think about it with the team, cause that would change how activation strategies work which would have an impact in all our SDKs. From the top of my head, this is not something we'll be implementing soon, but I'll have to talk to the team.

@derari 

Interesting use case.

The architecture of our SDKs is designed to evaluate feature flags quickly with minimum overhead when you do the actual isEnabled call. Generally, we advise against lazy loading properties because this adds overhead when you are doing the actual isEnabled call, which is when you want the evaluation to be as quick as possible because delays in this method is often impacting user experience. 

If I understand your use-case correctly, maybe you can keep a cache of your values that is periodically computed on an interval. That will allow you to space out when the values are computed and have them ready to be passed to the context without adding overhead when the codepath is actually triggered. Synching in the background like this will reduce the overhead of calling isEnabled.

Would that be a workable solution for this problem?

**Comment by derari** [comment]
I am currently using caching, but it is really the number of properties that is the problem here, so the cost of the intial request would still be high.

For now, I solved this with "meta feature flags" that allow me to disable individual context properties. E.g., if I know we will do a rollout based on product code, I will enable the product code, and when the rollout is done I disable it again. It's an okayish solution that works, so there is no urgency on my end. But it would be greatly appreciated if this feature could be added at some point.

**Comment by gastonfournier** [comment]
After giving it some thought, we've decided not to move forward with this feature. It could put some pressure on us since we wouldn't know if the SDK is slow because of some async functions. Plus, porting this to other SDKs would be quite a challenge, and we aim to keep feature parity as much as possible.
That said, maybe there's something about your use case we're not fully grasping. If you think this is a critical feature or if there's another angle we haven't considered, please let us know! We're always open to understanding different perspectives.
For now, we'll close this issue as "won't do," but we're happy to revisit it if needed.
