### ISSUE TITLE
Java client never fetches from server

### ISSUE THREAD

**Issue by ben-bourdin451** [Unleash/unleash-client-java#62]
I'm having trouble getting the Java client setup and running. Everything looks fine from the logs when running a simple test.

```java
UnleashConfig config = UnleashConfig.builder()
				.appName("test")
				.instanceId("localhost")
				.unleashAPI("http://localhost:4242/api/")
				.build();
Unleash client = new DefaultUnleash(config);
assertTrue(client.isEnabled("test-feature"));
```

I'm running client v3.1.2 and server locally v3.1.7. I'm able to connect to the server fine using curl and also while running the node client. Both return expected results. The only logs I can see are

```
09:56:04.579 [main] INFO  no.finn.unleash.repository.ToggleBackupHandlerFile - Unleash will try to load feature toggle states from temporary backup
09:56:04.579 [main] INFO  no.finn.unleash.repository.ToggleBackupHandlerFile - Unleash will try to load feature toggle states from temporary backup
09:56:04.590 [main] WARN  no.finn.unleash.repository.ToggleBackupHandlerFile -  Unleash could not find the backup-file '/var/folders/nd/1c9btckx64jdxkj94j7dy8400000gn/T//unleash-test-repo.json'. 
This is expected behavior the first time unleash runs in a new environment.
09:56:04.590 [main] WARN  no.finn.unleash.repository.ToggleBackupHandlerFile -  Unleash could not find the backup-file '/var/folders/nd/1c9btckx64jdxkj94j7dy8400000gn/T//unleash-test-repo.json'. 
This is expected behavior the first time unleash runs in a new environment.
```

When I add a backup file and specify it in the builder then the last 2 log messages disappear however the result is still wrong. When I add the expected feature flag to the backup file then the above test passes so it seems like it's only fetching from the 'local backup' without ever going out to the server.

From the node client I get the following log on the server: `New client registered with appName=ben-node-client and instanceId=ben-macbookpro` which I never get from the Java client.

Any help would be greatly appreciated! I really like this project and would love to get it running.
Thanks

**Comment by ivarconr** [comment]
Hi @ben-bourdin451, first of all thanks for your interest in the project. 

```java
assertTrue(client.isEnabled("test-feature"));
```

Unleash will try to fetch toggles from the server immediately in the background, but will not block for the first request to be completed. This might be the reason for your assert to fail. In a normal application setup where the webapp/api-server runs for a long time this is exactly what you want. The SDK will however synchronously read the local backup-file at startup, so that's why it works if you add the toggle manually. You can however instruct the Unleash SDK to do a synchronous fetch on initialisation via the `synchronousFetchOnInitialisation` option, and this should make your test succeed. You specify that like this:

```java
UnleashConfig config = UnleashConfig.builder()
				.appName("test")
				.instanceId("localhost")
				.unleashAPI("http://localhost:4242/api/")
				.synchronousFetchOnInitialisation(true)
				.build();
Unleash client = new DefaultUnleash(config);
assertTrue(client.isEnabled("test-feature"));
```
 

```bash
09:56:04.590 [main] WARN  no.finn.unleash.repository.ToggleBackupHandlerFile -  Unleash could not find the backup-file '/var/folders/nd/1c9btckx64jdxkj94j7dy8400000gn/T//unleash-test-repo.json'. 
This is expected behavior the first time unleash runs in a new environment.
```

This is expected behaviour first time your start the Unleash SDK as the client will try to create a backup-file first time it starts. If this happens multiple times in a while running your application it sounds like something is wrong. Based on the logs, i looks like to me it looks like you have started to instances of Unleash in your test, can that be correct?

**Comment by ben-bourdin451** [comment]
Thanks for the quick reply! I did notice the synchronous fetch option when setting up the client however I took it out since it didn't make a difference at the time.

I was perhaps being a bit lazy but I've now downloaded the source, ran it through the debugger and found the issue. I was getting a 400 response from the server for a GET on `api/client/features`. This is due to me not setting an 'instanceId' in the context of the client in the test. Weirdly I can't replicate this behaviour using curl.

IMO perhaps the only issue I can see from my original request is actually that the client fails silently with:
* no logs to show a 4XX error
* no exceptions being thrown back up to the caller

Debatably you might not want to throw any exceptions up the stack for fault tolerance, 4XX could but not 5XX. I guess my question here is how would my client or backend servers detect these type of errors? I haven't setup any monitoring yet so that could be the answer.

Feel free to close this issue and let me know if you would like me to open a different one or rename this to discuss monitoring/fault tolerance.

Thanks!

**Comment by ivarconr** [comment]
> I was getting a 400 response from the server for a GET on `api/client/features`. This is due to me not setting an 'instanceId' in the context of the client in the test. Weirdly I can't replicate this behaviour using curl.

This does not make sense at all. The client will generate a instanceId if it's not specified directly. 
- Would you mind debugging the client and see what is produced as instanceId in your setup. 
- Could you test to use `https://unleash.herokuapp.com/api/` as unleashAPI?

> no logs to show a 4XX error

I agree that this should be logged. I will address this in #63

> Debatably you might not want to throw any exceptions up the stack for fault tolerance, 4XX could but not 5XX. I guess my question here is how would my client or backend servers detect these type of errors? I haven't setup any monitoring yet so that could be the answer.

I think I would prefer the client to retry fetching as the errors might be due to glitches in the network. However it should provide hooks to tap in to this information and this was the idea behind #51. The node-client is already emits these kind of events.

**Comment by ben-bourdin451** [comment]
I agree that it doesn't make any sense at all, although I didn't really look into it too much 😅
I've replicated this using `https://unleash.herokuapp.com/api/`. Here is the config code to help you replicate:

```
UnleashConfig config = UnleashConfig.builder()
				.appName("test")
				.instanceId(null)
				.unleashAPI("https://unleash.herokuapp.com/api/")
				.synchronousFetchOnInitialisation(true)
				.build();
```

Thank you for the links to those issues, I like the idea of observables for error handling 👍

**Comment by ivarconr** [comment]
Thanks, I am able to reproduce. I will make a fix, the `instanceId` can not be null and the client should not accept this as a value.
