### ISSUE TITLE
Metric Bucket + Client Features Flag list

### ISSUE THREAD

**Issue by Green-Apple** [Unleash/unleash-client-java#85]
I noticed `no.finn.unleash.metric.MetricsBucket ` is a non-public class, is that intentional? I was hoping to retrieve the MetricBucket via the UnleashSubscriber.clientMetrics() event to capture a Set of the feature flags the client is checking for. This could be a quick way to identify feature flags that exist (and are being called) in the client, that may not exist on the server yet. Unless there is a better alternative way for the client to know what feature flags exist within the client code base. I know from the Unleash server side, for a given application, I can get a list of Feature flags that have been triggered on the client, but are not defined on the server. I'm trying to do a similar thing, just from the client side.

**Comment by ivarconr** [comment]
It's non public because it's subject to change in upcoming versions (I want to rethink the metrics part a bit to get  more derails, e.g. which strategy contributed to evaluating this toggle to true).

Your question is valid though. It would probably be nice if the clients expose metrics. I see multiple usages for this.
